import type { PortfolioItem } from "./portfolio";
import kl from '@/assets/img/portfolio/kl-itech-2.jpg'
import img1 from '@/assets/img/sample/gallery/img- (3).jpg'
import img2 from '@/assets/img/sample/gallery/img- (4).jpg'
import img3 from '@/assets/img/sample/gallery/img- (5).jpg'
import img4 from '@/assets/img/sample/gallery/img- (6).jpg'
import img5 from '@/assets/img/sample/gallery/img- (7).jpg'

export const portfolioItems: PortfolioItem[] = [
  // --- WEBSITE CATEGORY ---
  {
    id: "web-1",
    title: "KL iTech",
    image: kl.src,
    category: "website",
    date: "Nov, 2024",
    description: "Website Design and Development.",
  },
  {
    id: "web-2",
    title: "Gokul Santol",
    image: img2.src,
    category: "website",
    date: "Aug, 2024",
    description: "Website and WooCommerce Store.",
  },
  {
    id: "web-3",
    title: "Bioxgreen",
    image: img3.src,
    category: "website",
    date: "Oct, 2020",
    description: "Website and Digital Marketing.",
  },
  {
    id: "web-4",
    title: "Stanson",
    image: img4.src,
    category: "website",
    date: "Dec, 2021",
    description: "Website Design and Development.",
  },
  {
    id: "web-5",
    title: "Devoir",
    image: img5.src,
    category: "website",
    date: "Sep, 2023",
    description: "Website, SEO, and Digital Marketing.",
  },
  {
    id: "web-6",
    title: "Teyro",
    image: img1.src,
    category: "website",
    date: "May, 2022",
    description: "Website Development.",
  },
  {
    id: "web-7",
    title: "Grayeye IT",
    image: img2.src,
    category: "website",
    date: "Mar, 2022",
    description: "Website, Logo, and Brochure Design.",
  },
  {
    id: "web-8",
    title: "RV Interiors",
    image: img3.src,
    category: "website",
    date: "Jan, 2024",
    description: "Website Design and Development.",
  },
  {
    id: "web-9",
    title: "Qcloud",
    image: img4.src,
    category: "website",
    date: "Sep, 2021",
    description: "Website Development.",
  },
  {
    id: "web-10",
    title: "YS Ventures",
    image: img5.src,
    category: "website",
    date: "Aug, 2023",
    description: "Website Design.",
  },
  {
    id: "web-11",
    title: "Jd Jery",
    image: img1.src,
    category: "website",
    date: "May, 2020",
    description: "Website Design.",
  },
  {
    id: "web-12",
    title: "Recyclers Plaza",
    image: img2.src,
    category: "website",
    date: "Aug, 2023",
    description: "Website Development.",
  },
  {
    id: "web-13",
    title: "Indian Former",
    image: img3.src,
    category: "website",
    date: "May, 2021",
    description: "Website Design.",
  },
  {
    id: "web-14",
    title: "Blackstrom Energy",
    image: img4.src,
    category: "website",
    date: "Oct, 2022",
    description: "Website Design and Development.",
  },

  // --- LOGO CATEGORY ---
  {
    id: "logo-1",
    title: "Guhan Powers",
    image: img5.src,
    category: "logo",
    date: "Feb, 2025",
    description: "Logo Design.",
  },
  {
    id: "logo-2",
    title: "KL iTech",
    image: img1.src,
    category: "logo",
    date: "Jul, 2024",
    description: "Logo Design.",
  },
  {
    id: "logo-3",
    title: "Conworld Lines",
    image: img2.src,
    category: "logo",
    date: "Aug, 2024",
    description: "Logo Design.",
  },
  {
    id: "logo-4",
    title: "Flavoyage Exports",
    image: img3.src,
    category: "logo",
    date: "Sep, 2024",
    description: "Logo Design.",
  },
  {
    id: "logo-5",
    title: "Air Go",
    image: img4.src,
    category: "logo",
    date: "Oct, 2022",
    description: "Logo Design.",
  },
  {
    id: "logo-6",
    title: "Empower Beauty Wellness",
    image: img5.src,
    category: "logo",
    date: "Feb, 2024",
    description: "Logo Design.",
  },
  {
    id: "logo-7",
    title: "Hamsa",
    image: img1.src,
    category: "logo",
    date: "Jan, 2024",
    description: "Logo Design.",
  },
  {
    id: "logo-8",
    title: "Spark technologies",
    image: img2.src,
    category: "logo",
    date: "Mar, 2024",
    description: "Logo Design.",
  },
  {
    id: "logo-9",
    title: "DC Marine",
    image: img3.src,
    category: "logo",
    date: "Apr, 2022",
    description: "Logo Design.",
  },
  {
    id: "logo-10",
    title: "Galerie Infins",
    image: img4.src,
    category: "logo",
    date: "Mar, 2024",
    description: "Logo Design.",
  },
  {
    id: "logo-11",
    title: "Heera Wattec",
    image: img5.src,
    category: "logo",
    date: "Feb, 2023",
    description: "Logo Design.",
  },
  {
    id: "logo-12",
    title: "Pest Tech Global",
    image: img1.src,
    category: "logo",
    date: "Oct, 2023",
    description: "Logo Design.",
  },
  {
    id: "logo-13",
    title: "Solbec Energy",
    image: img2.src,
    category: "logo",
    date: "Sep, 2023",
    description: "Logo Design.",
  },
  {
    id: "logo-14",
    title: "Strategic SR",
    image: img3.src,
    category: "logo",
    date: "Nov, 2023",
    description: "Logo Design.",
  },
  {
    id: "logo-15",
    title: "Abirami",
    image: img4.src,
    category: "logo",
    date: "May, 2022",
    description: "Logo Design.",
  },
  {
    id: "logo-16",
    title: "Syndicate Women's Hostel",
    image: img5.src,
    category: "logo",
    date: "May, 2023",
    description: "Logo Design.",
  },
];